set number "mostrar numeros al costado izquierdo"
set mouse=a "Interactuar con el mouse dentro de vim"
set numberwidth=1 "setear el ancho de los numeros"
set clipboard+=unnamed "COPY => clipboard"
set clipboard=unnamedplus "COPY => clipboard, es necesario xclip"
syntax enable "Habilitar la sintaxis dentro de vim"
set showcmd "Mostrar los comandos que estoy ejecutando"
set ruler "Habilitar siempre la posicion"
set encoding=utf-8 "Setear la codificacion de archivos"
set showmatch "Mostrar el parentesis que cierra"
set sw=2 "Identacion con espacio en lugar de tab"
set relativenumber "Donde se encuentre el cursos es un 0 (number*k)"
set laststatus=2 "En vim que la barra de titulo siempre sea visible"
set noshowmode "No mostrar --INSERTAR--"
"set cursorline resaltará la línea actual en cada ventana y actualizará el resaltado a medida que se mueve el cursor."
